config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'

  concern :deletable do
    delete :index, on: :collection, action: :delete
  end

  resources :orders, except: [:destroy, :edit], concerns: :deletable do
    collection do
      get 'import'
      post 'import'
      post 'lookup'
    end
  end

  resources :loads, except: [:destroy, :edit], concerns: :deletable do
    member do
      get 'download'
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :download, :to => :read

    user ||= User.new

    if user.dispatcher?
      can :manage, :all
    elsif user.driver?
      can :read, Load
    end
  end
end

app/models/load.rb
class Load < ActiveRecord::Base
  has_many :orders, -> { order(:order) }
  accepts_nested_attributes_for :orders

  enum delivery_shift: [:morning, :noon, :evening]

  validates :delivery_date, :delivery_shift, presence: true
  validate :delivery_shift_occupation, :volume_excess

  scope :ordered_by_date, -> { order(:delivery_date, :delivery_shift) }

  AVAILABLE_VOLUME = 1400

  def load_number
    date = '00000000'
    date = delivery_date.strftime('%Y%m%d')
    "L#{date}#{delivery_shift[0].upcase}"
  end

  def initial_volume
    orders.select{ |order| !order.return }.inject(0){ |v, order| v + order.volume }
  end

  def total_volume
    orders.inject(0){ |v, order| v + order.volume }
  end

  def delivery_shift_occupation
    loads = Load.where(delivery_shift: Load.delivery_shifts[delivery_shift], delivery_date: delivery_date)
    loads = loads.where.not(id: id) if id
    errors.add(:base, "Delivery shift is already occupied") if loads.count > 0
  end

  def volume_excess
    volume = initial_volume()
    if volume > AVAILABLE_VOLUME
      errors.add(:base, "Inital truckload exceeds available volume in truck (#{AVAILABLE_VOLUME}ft3)")
      return
    end

    orders.sort_by(&:order).each { |order|
      if !order.return
        volume -= order.volume
      else
        volume += order.volume
        if volume > AVAILABLE_VOLUME
          errors.add(:base, "Excess of available volume in truck (#{AVAILABLE_VOLUME}ft3) while processing return on stop #{order.order}")
          break
        end
      end
    }
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :load

	enum delivery_shift: [:morning, :noon, :evening]
	enum mode: [:truckload]
	enum handling_unit_type: [:box]

  scope :ordered_by_date, -> { order(:delivery_date, :delivery_shift) }

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :trackable, :validatable
  enum role: [:dispatcher, :driver]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_path
  end
end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_load, only: [:show, :update, :download]
  authorize_resource

  def index
    @loads = Load.includes(:orders).ordered_by_date()
  end

  def show
  end

  def new
    @load = Load.new
  end

  def create
    prefill_ordering

    @load = Load.new(load_params)
    if @load.save
      return redirect_to load_url(@load)
    end
    render :new
  end

  def update
    prefill_ordering

    if @load.update(load_params)
      return redirect_to load_url(@load)
    end
    render :show
  end

  def delete
    loads = Load.where(id: params[:ids])
    loads.delete_all
    respond_to do |format|
      format.json { render :json => { redirect: loads_url } }
    end
  end

  def download
    pdf = render_to_string pdf: "#{@load.load_number}", layout: "pdf", template: "loads/show", viewport_size: '1920x995'
    send_data pdf, filename: "#{@load.load_number}.pdf"
  end

  private

  def prefill_ordering
    params[:load][:orders_attributes] = []

    params[:load][:order_ids].each_with_index do |id, i|
      params[:load][:orders_attributes].push({id: id, order: i}) if !id.blank?
    end
  end

  def find_load
    @load = Load.includes(:orders).find(params[:id])
  end

  def load_params
    params.require(:load).permit(
      :delivery_date,
      :delivery_shift,
      order_ids: [],
      orders_attributes: [:id, :order])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_order, only: [:show, :update]
  authorize_resource

  def index
    @orders = Order.ordered_by_date
  end

  def show
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      return redirect_to order_url(@order)
    end
    render :new
  end

  def update
    if @order.update(order_params)
      return redirect_to order_url(@order)
    end
    render :show
  end

  def import
    if request.post?
      begin
        @result = ImportOrders.new.run(params[:file], method(:permit_params))
      rescue Exception => e
        flash.now[:alert] = e.message
      end
    end
  end

  def delete
    orders = Order.where(id: params[:ids])
    orders.delete_all
    respond_to do |format|
      format.json { render :json => { redirect: orders_url } }
    end
  end

  def lookup
    ids = params[:ids]
    @orders = Order.where.not(id: ids).ordered_by_date
    render layout: 'modal'
  end

  private

  def find_order
    @order = Order.find(params[:id])
  end

  def order_params
    permit_params(params)
  end

  def permit_params(params)
    params.require(:order).permit(
      :purchase_order_number,
      :delivery_date,
      :delivery_shift,
      :origin_name,
      :origin_raw_line_1,
      :origin_city,
      :origin_state,
      :origin_zip,
      :origin_country,
      :client_name,
      :destination_raw_line_1,
      :destination_city,
      :destination_state,
      :destination_zip,
      :destination_country,
      :phone_number,
      :mode,
      :volume,
      :handling_unit_quantity,
      :handling_unit_type,
      :return)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def index
    redirect_to orders_url if current_user.dispatcher?
    redirect_to loads_url if current_user.driver?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bool_yes_no(bool)
    bool ? 'Yes' : 'No'
  end
end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def order_title(order)
    order.purchase_order_number.blank? ? 'N/A' : order.purchase_order_number
  end

  def origin_address(order)
    "#{order.origin_raw_line_1}, #{order.origin_city}, #{order.origin_state} #{order.origin_zip}"
  end

  def destination_address(order)
    "#{order.destination_raw_line_1}, #{order.destination_city}, #{order.destination_state} #{order.destination_zip}"
  end

  def delivery_date(order)
    date = []
    date << order.delivery_date if order.delivery_date != nil
    date << "#{order.delivery_shift.humanize}" if order.delivery_shift != nil
    return date.join(" ")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Larkin Supply
    == stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/" Larkin Supply
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            - if can? :index, Order
              li
                a href="#{orders_path}" Orders
            - if can? :index, Load
              li
                a href="#{loads_path}" Loads

          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              li
                a = current_user.email
              li
                = link_to "Sign out", destroy_user_session_path, method: :delete

    .container
      - if notice
        p.alert.alert-success = notice
      - if alert
        p.alert.alert-danger = alert
      == yield
    .modal-holder

app/views/layouts/modal.html.slim
.modal.fade role="dialog" tabindex="-1"
  .modal-dialog.modal-lg
    .modal-content
      == yield

app/views/layouts/pdf.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    meta charset="utf-8"
    == wicked_pdf_stylesheet_link_tag "application"
    == wicked_pdf_stylesheet_link_tag "pdf"
    == wicked_pdf_javascript_include_tag "application"
  body
    == yield

app/views/loads/_form.html.slim
- if @load.errors.any?
  .errors
    h2 = "#{pluralize(@load.errors.count, 'error')} prohibited this load from being saved:"
    ul
      - @load.errors.full_messages.each do |message|
        li = message

== form_for @load, html: {id: "load_form"} do |f|
  .toolbar
    - if can? :update, @load
      == f.submit "Save", class: "btn btn-default"
    - if @load.id
      a.btn.btn-default target="_blank" href="#{download_load_path(@load)}" Download
  .row
    .col-md-6
      .form-group
        == f.label :delivery_date
        == f.text_field :delivery_date, class: "form-control", "data-provide" => "datepicker", "data-date-format" => "yyyy-mm-dd", disabled: cannot?(:update, @load)


    .col-md-6
      .form-group
        == f.label :delivery_shift
        == f.select :delivery_shift, Load.delivery_shifts.map { |key, value| [key.humanize, key] }, { include_blank: true }, class: "form-control", disabled: cannot?(:update, @load)
  .row
    .col-md-6
      .form-group
        == f.label :total_volume
        == f.text_field :total_volume, class: "form-control", disabled: true
    .col-md-6
      .form-group
        == f.label :initial_volume
        == f.text_field :initial_volume, class: "form-control", disabled: true

  h2 Orders
  .toolbar
    - if can? :update, @load
      a.btn.btn-default.add-orders href="#{lookup_orders_path}" Add orders
  == hidden_field_tag "load[order_ids][]", nil
  == render 'orders/grid', orders: @load.orders, form: true, rearrangable: can?(:edit, Load), selectable: false, lookup: false

app/views/loads/edit.html.slim
h1 = "Loads > #{@load.load_number}"
== render "form"

app/views/loads/index.html.slim
h1 Loads

.toolbar
  - if can? :create, Load
    a.btn.btn-default href="#{new_load_path}" Create load
  - if can? :destroy, Load
    a.btn.btn-default.delete-btn.disabled href="#{loads_path}" Delete load(s)

.grid
  table.table.table-striped.table-condensed
    thead
      tr
        th
          input#select-all-checkbox type="checkbox"
        th Load Number
        th Delivery Date
        th Delivery Shift
        th Total Volume

    tbody
      - @loads.each do |load|
        tr
          td
            input.select-checkbox type="checkbox" value="#{load.id}"
          td == link_to load.load_number, load_path(load)
          td = load.delivery_date
          td = load.delivery_shift.to_s.humanize
          td = load.total_volume

app/views/loads/new.html.slim
h1 Loads > New

== render "form"

app/views/loads/show.html.slim
h1 = "Loads > #{@load.load_number}"
== render "form"

app/views/loads/show.pdf.slim
.foo Bar

app/views/orders/_form.html.slim
== form_for @order do |f|
  .toolbar
    == f.submit "Save", class: "btn btn-default"
  .row
    .col-md-6
      .form-group
        == f.label :purchase_order_number
        == f.text_field :purchase_order_number, class: "form-control"

      .form-group
        == f.label :delivery_date
        == f.text_field :delivery_date, class: "form-control", "data-provide" => "datepicker", "data-date-format" => "yyyy-mm-dd"

      .form-group
        == f.label :delivery_shift
        == f.select :delivery_shift, Order.delivery_shifts.map { |key, value| [key.humanize, key] }, { include_blank: true }, class: "form-control"

      .form-group
        == f.label :origin_name
        == f.text_field :origin_name, class: "form-control"

      .form-group
        == f.label :origin_raw_line_1
        == f.text_field :origin_raw_line_1, class: "form-control"

      .form-group
        == f.label :origin_city
        == f.text_field :origin_city, class: "form-control"

      .form-group
        == f.label :origin_state
        == f.text_field :origin_state, class: "form-control"

      .form-group
        == f.label :origin_zip
        == f.text_field :origin_zip, class: "form-control"

      .form-group
        == f.label :origin_country
        == f.text_field :origin_country, class: "form-control"

      .form-group
        == f.label :client_name
        == f.text_field :client_name, class: "form-control"
      .form-group
        == f.label :return
        == f.select :return, [["No", false], ["Yes", true]], { }, class: "form-control"

    .col-md-6
      .form-group
        == f.label :destination_raw_line_1
        == f.text_field :destination_raw_line_1, class: "form-control"

      .form-group
        == f.label :destination_city
        == f.text_field :destination_city, class: "form-control"

      .form-group
        == f.label :destination_state
        == f.text_field :destination_state, class: "form-control"

      .form-group
        == f.label :destination_zip
        == f.text_field :destination_zip, class: "form-control"

      .form-group
        == f.label :destination_country
        == f.text_field :destination_country, class: "form-control"

      .form-group
        == f.label :phone_number
        == f.text_field :phone_number, class: "form-control"

      .form-group
        == f.label :mode
        == f.select :mode, Order.modes.map { |key, value| [key.humanize, key] }, { }, class: "form-control"

      .form-group
        == f.label :volume
        == f.text_field :volume, class: "form-control"

      .form-group
        == f.label :handling_unit_quantity
        == f.text_field :handling_unit_quantity, class: "form-control"

      .form-group
        == f.label :handling_unit_type
        == f.select :handling_unit_type, Order.handling_unit_types.map { |key, value| [key.humanize, key] }, { }, class: "form-control"

app/views/orders/_grid.html.slim
.grid
  table.table.table-striped.table-condensed
    thead
      tr
        - if selectable
          th
            - if selectable[:all]
              input#select-all-checkbox type="checkbox"
        th Order
        th Delivery&nbsp;Date
        - if !lookup
          th Origin&nbsp;Name
        th Origin&nbsp;Address
        th Destination&nbsp;Address
        th Client&nbsp;Name
        th Phone
        th Return
        - if !lookup
          th Type
        th Qty
        th Volume
        - if rearrangable
          th.commands
    tbody
      - orders.each do |order|
        tr
          - if form
            input type="hidden" name="load[order_ids][]" value="#{order.id}"
          - if selectable
            td
              input.select-checkbox type="checkbox" value="#{order.id}"
          td == link_to order_title(order), order_path(order)
          td = delivery_date(order)
          - if !lookup
            td = order.origin_name
          td = origin_address(order)
          td = destination_address(order)
          td = order.client_name
          td = order.phone_number
          td = bool_yes_no(order.return)
          - if !lookup
            td = order.handling_unit_type.to_s.humanize
          td = order.handling_unit_quantity
          td = order.volume
          - if rearrangable
            td.commands
              .btn-group.btn-group-xs
                button.btn.btn-default.glyphicon.glyphicon-menu-up.move-up
                button.btn.btn-default.glyphicon.glyphicon-menu-down.move-down
                button.btn.btn-default.glyphicon.glyphicon-remove.remove

app/views/orders/edit.html.slim
h1 = "Orders > #{order_title(@order)}"

== render "form"

app/views/orders/import.html.slim
h1 Orders > Import

- if @result
  .alert.alert-success
    p = "Successfully imported #{@result[:imported]} order(s)"
    - if @result[:failures].size > 0
      p = "Failures count - #{@result[:failures].size}:"
      - @result[:failures].take(5).each_with_index do |failure, i|
        p
          div = failure.inspect
          div = @result[:messages][i]

== form_tag import_orders_path, multipart: true do
  .form-group
    label for="file-input" Select a csv file with orders
    input#file-input type="file" name="file"
  input.btn.btn-default type="submit" value="Import CSV" data-disable-with="Importing..."

app/views/orders/index.html.slim
h1 Orders

.toolbar
  a.btn.btn-default href="#{new_order_path}" Create order
  a.btn.btn-default.delete-btn.disabled href="#{orders_path}" Delete order(s)
  a.btn.btn-default href="#{import_orders_path}" Import from CSV

== render 'grid', orders: @orders, form: false, rearrangable: false, selectable: { all: true }, lookup: false

app/views/orders/lookup.html.slim
.modal-header
  button.close aria-label="Close" data-dismiss="modal" type="button"
    span aria-hidden="true" ×
  h4.modal-title Select orders
.modal-body
  == render 'grid', orders: @orders, form: false, rearrangable: false, selectable: { all: false }, lookup: true

.modal-footer
  button.btn.btn-default data-dismiss="modal" type="button" Cancel
  button.btn.btn-primary.btn-ok type="button" Select

app/views/orders/new.html.slim
h1 Orders > New

== render "form"

app/views/orders/show.html.slim
h1 = "Orders > #{order_title(@order)}"

== render "form"